# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGM4MTI0NTYwNGVlMWYwNWZhNWNkMjk4N2U1MWNkN2I0ZThiZmZkNjJmNmRiNzUyYjAyMWU5NTNjMzA4NGI2ZDI2NGQzZDgyYmUwMDg2YzVlNzdiNTc1NjUyMzQyN2JmZGE1NTZhYmIyMTgyNzdiZmIwNWM5MjAyNTYxYWZkMzA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
